name: 360nami-free-api
services:
  360nami-free-api:
    container_name: 360nami-free-api
    build: .
    restart: always
    ports:
      - "8000:8000"
    environment:
      - TZ=Asia/Shanghai
      - |
        NAMI_AUTH_LIST=[
          {
            "COOKIE": "",
            "ACCESS_TOKEN": "",
            "AUTH_TOKEN": ""
          }
        ]